adminUser:
  password: vault:alevat/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins@alevat.com
  token: vault:alevat/pipelineUser:token
  username: alevat-jenkins
prow:
  hmacToken: vault:alevat/prow:hmacToken
